version: '3'
services:
  traefik:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "81:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./conf/traefik.toml:/etc/traefik/traefik.toml
      - ./conf/acme.json:/acme.json
      - ./certs:/certs
      - ./traefik.log:/traefik.log
    container_name: traefik
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - traefik
  nginx:
    build: ./docker/nginx
    expose:
      - 80
    volumes:
      - ../:/var/www
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/sites-enabled:/etc/nginx/sites-enabled
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=${NGINX_HOSTS}
    command: /bin/sh -c "/usr/local/bin/wait && nginx -g 'daemon off;'"
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 100
      WAIT_SLEEP_INTERVAL: 3
    links:
      - php-fpm
    depends_on:
      - db
      - traefik
    networks:
      - traefik
  php-fpm:
    build: ./docker/php-fpm
    labels:
      - traefik.enable=false
    volumes:
      - ../:/var/www
    networks:
      - traefik
    links:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - 33306:3306
    labels:
      - traefik.enable=false
    networks:
      - traefik
networks:
  traefik:
    external: true
